# Links de Navegação
#   Para ligar a um widget da homepage, use URL como '#nome-do-widget'.
#   O parâmetro weight define a ordem dos links no menu.

main:
  - name: Pesquisa
    url: /research
    weight: 10
  - name: Membros
    url: /people
    weight: 20
  - name: Publicações
    url: /publication
    weight: 30
  - name: Divulgação
    url: /post
    weight: 40
  - name: Oportunidades
    url: /opportunities
    weight: 50
  - name: Contato
    url: /contact
    weight: 60
